In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
%matplotlib inline

In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

In [3]:
#bigquery-public-data.github_repos.[TABLENAME]

In [4]:
# Get Started 
# source: https://www.kaggle.com/mrisdal/safely-analyzing-github-projects-popular-licenses/data
import pandas as pd
# https://github.com/SohierDane/BigQuery_Helper
from bq_helper import BigQueryHelper

# 
bq_assistant = BigQueryHelper("bigquery-public-data", "ncaa_basketball")


# list the tables
bq_assistant.list_tables()


# list table schema
bq_assistant.table_schema("mbb_teams")

# list first few rows
bq_assistant.head("mbb_teams", num_rows=10)


# write a query
QUERY = """
select market, venue_city, venue_capacity
FROM `bigquery-public-data.ncaa_basketball.mbb_teams`
"""
# estimate query size ()
bq_assistant.estimate_query_size(QUERY) # in gb
df = bq_assistant.query_to_pandas_safe(QUERY) # will not execute query over size 1 GB
df.head()

DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started

In [5]:
# home team
QUERY = """select h_points_game, h_rebounds, h_turnovers, a_turnovers, h_blocks, h_assists, h_steals, h_three_points_made, h_two_points_made, h_free_throws_made 
from `bigquery-public-data.ncaa_basketball.mbb_games_sr` 
where season >= 2014
order by h_rebounds asc"""

df = bq_assistant.query_to_pandas_safe(QUERY) # will not execute query over size 1 GB
df.head()
df.corr()
#df.describe()

,h_points_game,h_rebounds,h_turnovers,a_turnovers,h_blocks,h_assists,h_steals,h_three_points_made,h_two_points_made,h_free_throws_made
h_points_game,1.000000,0.372090,-0.053280,0.058634,0.132923,0.650784,0.242984,0.511349,0.611817,0.362008
h_rebounds,0.372090,1.000000,0.149848,-0.147556,0.258233,0.257996,0.046980,0.053034,0.351085,0.158174
h_turnovers,-0.053280,0.149848,1.000000,0.150527,0.070959,-0.034422,0.090943,-0.064222,-0.064685,0.098215
a_turnovers,0.058634,-0.147556,0.150527,1.000000,-0.032669,0.028011,0.515239,-0.001989,0.037323,0.068700
h_blocks,0.132923,0.258233,0.070959,-0.032669,1.000000,0.127637,0.049192,-0.001933,0.144811,0.056378
h_assists,0.650784,0.257996,-0.034422,0.028011,0.127637,1.000000,0.192525,0.525014,0.416700,-0.084219
h_steals,0.242984,0.046980,0.090943,0.515239,0.049192,0.192525,1.000000,0.037574,0.250885,0.063358
h_three_points_made,0.511349,0.053034,-0.064222,-0.001989,-0.001933,0.525014,0.037574,1.000000,-0.189483,-0.135969
h_two_points_made,0.611817,0.351085,-0.064685,0.037323,0.144811,0.416700,0.250885,-0.189483,1.000000,-0.004547
h_free_throws_made,0.362008,0.158174,0.098215,0.068700,0.056378,-0.084219,0.063358,-0.135969,-0.004547,1.000000

In [6]:
X = df.drop(['h_points_game'], axis=1)
X.head()

,h_rebounds,h_turnovers,a_turnovers,h_blocks,h_assists,h_steals,h_three_points_made,h_two_points_made,h_free_throws_made
0,0,0,16,0,0,0,0,0,0
1,0,0,16,0,0,0,0,0,0
2,0,0,21,0,0,0,0,0,0
3,0,0,8,0,0,0,0,0,0
4,10,12,15,4,13,4,5,19,10

In [7]:
y=df['h_points_game']
y.head()

0    79
1    69
2    51
3    26
4    63
Name: h_points_game, dtype: int64

In [8]:
# 1. Import the Estimator class you will use
from sklearn.linear_model import LinearRegression
# 2. Create an instance of the class
ml_reg = LinearRegression()
# 3. Use the fit method of the instance
ml_reg.fit(X, y)
# 4. Use the predict method to get the predictions
y_pred_ml_reg = ml_reg.predict(X)

In [9]:
pd.Series(ml_reg.coef_, index=X.columns).sort_values(ascending=False).round(2)

h_three_points_made    2.97
h_two_points_made      1.98
h_free_throws_made     0.99
h_assists              0.01
a_turnovers            0.00
h_blocks               0.00
h_rebounds            -0.00
h_steals              -0.01
h_turnovers           -0.01
dtype: float64

In [10]:
ml_reg.intercept_.round(3)

0.787

In [11]:
from sklearn.metrics import mean_squared_error, r2_score
# The mean squared error
print("Mean squared error: %.2f"
      % mean_squared_error(y, y_pred_ml_reg))

Mean squared error: 1.33

In [12]:
# away team
QUERY = """select a_points_game, a_rebounds, a_turnovers, h_turnovers, a_blocks, a_assists, a_steals, a_three_points_made, a_two_points_made, a_free_throws_made
from `bigquery-public-data.ncaa_basketball.mbb_games_sr` 
where season >= 2014
"""

df = bq_assistant.query_to_pandas_safe(QUERY) # will not execute query over size 1 GB
df.head()
df.corr()
#df.describe()

,a_points_game,a_rebounds,a_turnovers,h_turnovers,a_blocks,a_assists,a_steals,a_three_points_made,a_two_points_made,a_free_throws_made
a_points_game,1.000000,0.292617,-0.047056,0.072148,0.125121,0.551575,0.153373,0.503709,0.537641,0.457634
a_rebounds,0.292617,1.000000,0.395735,-0.120440,0.332521,0.390353,0.215109,0.251389,0.547347,0.391439
a_turnovers,-0.047056,0.395735,1.000000,0.150527,0.138080,0.175711,0.256382,0.130442,0.199140,0.210840
h_turnovers,0.072148,-0.120440,0.150527,1.000000,-0.036750,-0.003331,0.620528,-0.041256,0.024117,0.092614
a_blocks,0.125121,0.332521,0.138080,-0.036750,1.000000,0.174788,0.114868,0.086024,0.225282,0.161566
a_assists,0.551575,0.390353,0.175711,-0.003331,0.174788,1.000000,0.229442,0.606499,0.473766,0.160438
a_steals,0.153373,0.215109,0.256382,0.620528,0.114868,0.229442,1.000000,0.123725,0.306362,0.215306
a_three_points_made,0.503709,0.251389,0.130442,-0.041256,0.086024,0.606499,0.123725,1.000000,0.027107,0.076620
a_two_points_made,0.537641,0.547347,0.199140,0.024117,0.225282,0.473766,0.306362,0.027107,1.000000,0.266731
a_free_throws_made,0.457634,0.391439,0.210840,0.092614,0.161566,0.160438,0.215306,0.076620,0.266731,1.000000

In [13]:
X = df.drop(['a_points_game'], axis=1)
X.head()

,a_rebounds,a_turnovers,h_turnovers,a_blocks,a_assists,a_steals,a_three_points_made,a_two_points_made,a_free_throws_made
0,37,15,23,4,13,13,9,17,8
1,34,7,23,4,13,16,7,20,23
2,31,12,1,7,16,0,11,14,8
3,35,17,25,5,12,12,4,20,15
4,27,18,28,3,12,14,4,21,11

In [14]:
y=df['a_points_game']
y.head()

0    69
1    84
2    69
3    67
4    65
Name: a_points_game, dtype: int64

In [15]:
# 1. Import the Estimator class you will use
from sklearn.linear_model import LinearRegression
# 2. Create an instance of the class
ml_reg = LinearRegression()
# 3. Use the fit method of the instance
ml_reg.fit(X, y)
# 4. Use the predict method to get the predictions
y_pred_ml_reg = ml_reg.predict(X)

In [16]:
pd.Series(ml_reg.coef_, index=X.columns).sort_values(ascending=False).round(2)

a_three_points_made    2.14
a_two_points_made      1.41
a_free_throws_made     0.81
h_turnovers            0.60
a_assists              0.07
a_blocks              -0.03
a_rebounds            -0.28
a_turnovers           -0.60
a_steals              -0.91
dtype: float64

In [17]:
ml_reg.intercept_.round(3)

33.283

In [18]:
from sklearn.metrics import mean_squared_error, r2_score
# The mean squared error
print("Mean squared error: %.2f"
      % mean_squared_error(y, y_pred_ml_reg))

Mean squared error: 40.28